theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  menu:
    primary:
      level_2:
        title:
          active: true
  summary:
    position: hero
  search:
    active: true
    position: footer
  logo:
    header:
      default: /assets/images/logo.png
      darkmode: /assets/images/logo-on-red.png
    footer: /assets/images/logo-paris8.svg