theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
    position: footer
  logo:
    header: /assets/images/logo.png
    footer: /assets/images/logo-baseline.png